{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "government-portal.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "government-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  Oidc__ClientSecret: {{ .Values.secret.oidcClientSecret | quote }}
{{- end }}