apiVersion: v1
kind: Service
metadata:
  name: {{ include "government-portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "government-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "government-portal.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http