apiVersion: v1
kind: Service
metadata:
  name: {{ include "organization-registry.fullname" . }}-api
  labels:
    {{- include "organization-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "organization-registry.api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: http