apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "organization-registry.fullname" . }}-config
  labels:
    {{- include "organization-registry.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  Jwt__Authority: {{ .Values.config.jwtAuthority | quote }}
  Jwt__Audience: {{ .Values.config.jwtAudience | quote }}
  PersonRegistry__BaseUrl: {{ .Values.config.personRegistryBaseUrl | quote }}
  OrganizationApi__BaseUrl: {{ .Values.config.organizationApiBaseUrl | quote }}
  Oidc__PublicBaseUrl: {{ .Values.config.publicWebBaseUrl | quote }}
  Oidc__Authority: {{ .Values.config.oidcAuthority | quote }}
  Oidc__ClientId: {{ .Values.config.oidcClientId | quote }}
  Oidc__RequireHttpsMetadata: {{ .Values.config.oidcRequireHttpsMetadata | quote }}
  {{- if .Values.web.dataProtection.enabled }}
  DataProtection__KeysPath: "/var/lib/organization-registry/keys"
  {{- end }}