{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "organization-registry.fullname" . }}-secret
  labels:
    {{- include "organization-registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ include "organization-registry.connectionString" . | quote }}
  Oidc__ClientSecret: {{ .Values.secret.oidcClientSecret | quote }}
{{- end }}