apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ego.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ego.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.aspnetcoreEnvironment | quote }}
  Keycloak__Authority: {{ .Values.config.keycloak.authority | quote }}
  {{- range $index, $audience := .Values.config.keycloak.audiences }}
  Keycloak__Audiences__{{ $index }}: {{ $audience | quote }}
  {{- end }}
  Keycloak__RequireHttpsMetadata: {{ .Values.config.keycloak.requireHttpsMetadata | quote }}
