{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ego.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ego.labels" . | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: {{ include "ego.connectionString" . | quote }}
{{- end }}
