apiVersion: v1
kind: Service
metadata:
  name: {{ include "election-service.fullname" . }}-web
  labels:
    {{- include "election-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    {{- include "election-service.web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.service.port }}
      targetPort: http