// <auto-generated />
using System;
using ElectionService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ElectionService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ElectionDbContext))]
    [Migration("20260731125826_AddElectionPublicVisibility")]
    partial class AddElectionPublicVisibility
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ElectionService.Domain.Entities.AnonymousBallot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceiptHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TerritoryCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId", "ReceiptHash")
                        .IsUnique();

                    b.HasIndex("ElectionId", "SelectionId", "TerritoryCode");

                    b.ToTable("AnonymousBallots");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.Candidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PartyListId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WinnerSelectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WinnerSelectedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PartyListId", "PersonId")
                        .IsUnique()
                        .HasFilter("\"PersonId\" IS NOT NULL");

                    b.HasIndex("PartyListId", "Position")
                        .IsUnique();

                    b.ToTable("Candidates", t =>
                        {
                            t.HasCheckConstraint("CK_Candidates_WinnerAudit", "(NOT \"IsWinner\" AND \"WinnerSelectedAt\" IS NULL AND \"WinnerSelectedByPersonId\" IS NULL) OR (\"IsWinner\" AND \"WinnerSelectedAt\" IS NOT NULL AND \"WinnerSelectedByPersonId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.CertificationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CertifierPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId", "CertifierPersonId")
                        .IsUnique();

                    b.ToTable("CertificationDecisions");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.Election", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CertificationQuorum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CertifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("CredentialHashKeyVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("EligibilityMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("EligibleVoterCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HistoricalInvalidBallotCount")
                        .HasColumnType("integer");

                    b.Property<int?>("HistoricalParticipatingVoterCount")
                        .HasColumnType("integer");

                    b.Property<string>("HistoricalSourceReference")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ImportedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsHistorical")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPubliclyVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SeatCount")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TerritoryCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VotingEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("VotingStartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Elections", t =>
                        {
                            t.HasCheckConstraint("CK_Elections_EligibleVoterCount", "\"EligibleVoterCount\" IS NULL OR \"EligibleVoterCount\" >= 0");

                            t.HasCheckConstraint("CK_Elections_HistoricalInvalidBallotCount", "\"HistoricalInvalidBallotCount\" IS NULL OR \"HistoricalInvalidBallotCount\" >= 0");

                            t.HasCheckConstraint("CK_Elections_HistoricalMetadata", "(\"IsHistorical\" AND \"HistoricalSourceReference\" IS NOT NULL AND \"ImportedAt\" IS NOT NULL AND \"ImportedByPersonId\" IS NOT NULL AND \"HistoricalParticipatingVoterCount\" IS NOT NULL AND \"HistoricalInvalidBallotCount\" IS NOT NULL) OR (NOT \"IsHistorical\" AND \"HistoricalSourceReference\" IS NULL AND \"ImportedAt\" IS NULL AND \"ImportedByPersonId\" IS NULL AND \"HistoricalParticipatingVoterCount\" IS NULL AND \"HistoricalInvalidBallotCount\" IS NULL)");

                            t.HasCheckConstraint("CK_Elections_HistoricalParticipatingVoterCount", "\"HistoricalParticipatingVoterCount\" IS NULL OR \"HistoricalParticipatingVoterCount\" >= 0");

                            t.HasCheckConstraint("CK_Elections_HistoricalParticipationWithinEligible", "\"EligibleVoterCount\" IS NULL OR \"HistoricalParticipatingVoterCount\" IS NULL OR \"HistoricalParticipatingVoterCount\" <= \"EligibleVoterCount\"");

                            t.HasCheckConstraint("CK_Elections_SeatCount", "\"SeatCount\" IS NULL OR \"SeatCount\" > 0");
                        });
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.ElectionResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SelectionLabel")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SelectionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TerritoryCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId", "SelectionId", "TerritoryCode")
                        .IsUnique();

                    b.ToTable("ElectionResults", t =>
                        {
                            t.HasCheckConstraint("CK_ElectionResults_VoteCount", "\"VoteCount\" >= 0");
                        });
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.ElectionTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId", "ChangedAt");

                    b.ToTable("ElectionTransitions");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.ParticipationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CredentialHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("RecordedOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId", "Channel", "CredentialHash")
                        .IsUnique();

                    b.ToTable("ParticipationRecords");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.PartyList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ListName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("PartyOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("PartyRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId", "PartyOrganizationId")
                        .IsUnique();

                    b.HasIndex("ElectionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("PartyLists");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.ReferendumOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId", "Code")
                        .IsUnique();

                    b.HasIndex("ElectionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("ReferendumOptions");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.VoterRollEntry", b =>
                {
                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AddedByPersonId")
                        .HasColumnType("uuid");

                    b.HasKey("ElectionId", "PersonId");

                    b.ToTable("VoterRollEntries");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.VotingInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByPersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ElectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("UsedOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId", "TokenHash")
                        .IsUnique();

                    b.ToTable("VotingInvitations");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.AnonymousBallot", b =>
                {
                    b.HasOne("ElectionService.Domain.Entities.Election", null)
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.Candidate", b =>
                {
                    b.HasOne("ElectionService.Domain.Entities.PartyList", "PartyList")
                        .WithMany("Candidates")
                        .HasForeignKey("PartyListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartyList");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.CertificationDecision", b =>
                {
                    b.HasOne("ElectionService.Domain.Entities.Election", null)
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.ElectionResult", b =>
                {
                    b.HasOne("ElectionService.Domain.Entities.Election", null)
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.ElectionTransition", b =>
                {
                    b.HasOne("ElectionService.Domain.Entities.Election", null)
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.ParticipationRecord", b =>
                {
                    b.HasOne("ElectionService.Domain.Entities.Election", null)
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.PartyList", b =>
                {
                    b.HasOne("ElectionService.Domain.Entities.Election", "Election")
                        .WithMany("PartyLists")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.ReferendumOption", b =>
                {
                    b.HasOne("ElectionService.Domain.Entities.Election", "Election")
                        .WithMany("ReferendumOptions")
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.VoterRollEntry", b =>
                {
                    b.HasOne("ElectionService.Domain.Entities.Election", null)
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.VotingInvitation", b =>
                {
                    b.HasOne("ElectionService.Domain.Entities.Election", null)
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.Election", b =>
                {
                    b.Navigation("PartyLists");

                    b.Navigation("ReferendumOptions");
                });

            modelBuilder.Entity("ElectionService.Domain.Entities.PartyList", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
