apiVersion: v1
kind: Secret
metadata:
  name: election-studio-youtube
  labels:
    app.kubernetes.io/name: election-studio
    app.kubernetes.io/part-of: election-service
type: Opaque
stringData:
  stream-url: rtmps://a.rtmps.youtube.com/live2/REPLACE_WITH_YOUR_STREAM_KEY
